4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:

1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).
2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).

3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L).

In [ ]:
def convert(choice, value):
    """
    Convert units based on the user's choice.

    Parameters:
    choice (int): Conversion option selected by the user
    value (float): Value to convert

    Returns:
    float: Converted value
    """

    if choice == 1:
        return value * 3.28      # meters to feet
    elif choice == 2:
        return value / 3.28      # feet to meters
    elif choice == 3:
        return value * 2.2       # kg to pounds
    elif choice == 4:
        return value / 2.2       # pounds to kg
    elif choice == 5:
        return value * 0.26      # liters to gallons
    elif choice == 6:
        return value / 0.26      # gallons to liters


print("Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Choose conversion (1-6): "))
    value = float(input("Enter value: "))

    result = convert(choice, value)
    print("Converted value:", result)

except:
    print("Invalid input. Please enter numbers only.")

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion (1-6): 4
Enter value: 68
Converted value: 30.909090909090907


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.


In [ ]:
def find_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: sum of the numbers
    """
    return sum(numbers)


def find_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: average value
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum number in a list.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: maximum value
    """
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum number in a list.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: minimum value
    """
    return min(numbers)


print("Math Operations Program")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = int(input("Choose operation (1-4): "))

    user_input = input("Enter numbers separated by spaces: ")

    numbers = [float(x) for x in user_input.split()]

    if len(numbers) == 0:
        print("Error: The list cannot be empty.")

    elif choice == 1:
        print("Sum =", find_sum(numbers))

    elif choice == 2:
        print("Average =", find_average(numbers))

    elif choice == 3:
        print("Maximum =", find_max(numbers))

    elif choice == 4:
        print("Minimum =", find_min(numbers))

    else:
        print("Invalid choice.")

except ValueError:
    print("Error: Please enter valid numbers.")

Math Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Choose operation (1-4): 3
Enter numbers separated by spaces: 17 23 45 76 57
Maximum = 76.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Returns every other element from the list starting from the first element.

    Parameters:
    lst (list): The input list

    Returns:
    list: A new list containing every other element
    """
    return lst[::2]


numbers = [10, 20, 30, 40, 50, 60]

result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [10, 20, 30, 40, 50, 60]
Every other element: [10, 30, 50]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from index start to end (inclusive).

    Parameters:
    lst (list): The original list
    start (int): Starting index
    end (int): Ending index

    Returns:
    list: Sublist from start to end
    """
    return lst[start:end+1]


numbers = [10, 20, 30, 40, 50, 60]

result = get_sublist(numbers, 1, 3)

print("Original list:", numbers)
print("Sublist:", result)

Original list: [10, 20, 30, 40, 50, 60]
Sublist: [20, 30, 40]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Returns the reversed version of a list using slicing.

    Parameters:
    lst (list): The original list

    Returns:
    list: Reversed list
    """
    return lst[::-1]


numbers = [10, 20, 30, 40, 50]

result = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", result)

Original list: [10, 20, 30, 40, 50]
Reversed list: [50, 40, 30, 20, 10]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
    lst (list): The original list

    Returns:
    list: A new list without the first and last elements
    """
    return lst[1:-1]

numbers = [10, 20, 30, 40, 50, 60]

result = remove_first_last(numbers)

print("Original list:", numbers)
print("New list:", result)

Original list: [10, 20, 30, 40, 50, 60]
New list: [20, 30, 40, 50]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list.

    Parameters:
    lst (list): The original list
    n (int): Number of elements to extract

    Returns:
    list: A new list containing the first n elements
    """
    return lst[:n]

numbers = [10, 20, 30, 40, 50, 60]

result = get_first_n(numbers, 4)

print("Original list:", numbers)
print("First n elements:", result)

Original list: [10, 20, 30, 40, 50, 60]
First n elements: [10, 20, 30, 40]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
    lst (list): The original list
    n (int): Number of elements to extract from the end

    Returns:
    list: A new list containing the last n elements
    """
    return lst[-n:]

numbers = [10, 20, 30, 40, 50, 60]

result = get_last_n(numbers, 3)

print("Original list:", numbers)
print("Last n elements:", result)

Original list: [10, 20, 30, 40, 50, 60]
Last n elements: [40, 50, 60]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Returns every second element from the list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The original list

    Returns:
    list: A new list of elements in reverse order skipping one element
    """
    return lst[-2::-2]

numbers = [10, 20, 30, 40, 50, 60, 70]

result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reversed skip list:", result)

Original list: [10, 20, 30, 40, 50, 60, 70]
Reversed skip list: [60, 40, 20]


4.3 Exercise on Nested List:

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list (list of lists)

    Returns:
    list: A flattened list with all elements in a single dimension
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

nested_list = [[10, 20], [30, 40, 50], [60]]

result = flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[10, 20], [30, 40, 50], [60]]
Flattened list: [10, 20, 30, 40, 50, 60]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Returns the element from a nested list at the specified indices.

    Parameters:
    lst (list): The nested list
    indices (list): A list of indices specifying the path to the element

    Returns:
    element: The element at the specified indices
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

nested_list = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
indices = [2, 1]  # Access the element in 3rd row, 2nd column

result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print("Element at indices", indices, ":", result)

Nested list: [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
Element at indices [2, 1] : 80


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers or other nested lists

    Returns:
    int/float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # recursive call for sublist
        else:
            total += item
    return total


nested_list = [[10, 20], [30, [40, 50]], 60]

result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[10, 20], [30, [40, 50]], 60]
Sum of all elements: 210


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list
    elem (any): The element to remove

    Returns:
    list: Modified nested list with the element removed
    """
    new_list = []
    for sublist in lst:
        # Remove the element from each sublist
        filtered = [x for x in sublist if x != elem]
        new_list.append(filtered)
    return new_list

nested_list = [[10, 20], [30, 20], [40, 50]]
element_to_remove = 20

result = remove_element(nested_list, element_to_remove)

print("Original nested list:", nested_list)
print("Nested list after removing", element_to_remove, ":", result)

Original nested list: [[10, 20], [30, 20], [40, 50]]
Nested list after removing 20 : [[10], [30], [40, 50]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers or other nested lists

    Returns:
    int/float: Maximum element in the nested list
    """
    max_value = float('-inf')  # Start with negative infinity
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursive call
        else:
            max_value = max(max_value, item)
    return max_value

nested_list = [[10, 20], [30, [40, 50]], 60]

result = find_max(nested_list)

print("Nested list:", nested_list)
print("Maximum element:", result)

Nested list: [[10, 20], [30, [40, 50]], 60]
Maximum element: 60


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts the number of times a specific element appears in a nested list.

    Parameters:
    lst (list): A nested list
    elem (any): The element to count

    Returns:
    int: Number of occurrences of the element
    """
    count = 0
    for sublist in lst:
        for item in sublist:
            if item == elem:
                count += 1
    return count

nested_list = [[10, 20], [20, 30], [40, 20]]
element_to_count = 20

result = count_occurrences(nested_list, element_to_count)

print("Nested list:", nested_list)
print(f"Number of occurrences of {element_to_count}:", result)

Nested list: [[10, 20], [20, 30], [40, 20]]
Number of occurrences of 20: 3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): A deeply nested list

    Returns:
    list: A flattened list containing all elements
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[10, 20], [30, 40]], [[50, 60], [70, 80]]]

result = deep_flatten(nested_list)

print("Original nested list:", nested_list)
print("Deep flattened list:", result)

Original nested list: [[[10, 20], [30, 40]], [[50, 60], [70, 80]]]
Deep flattened list: [10, 20, 30, 40, 50, 60, 70, 80]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers

    Returns:
    float: Average of all elements
    """
    def flatten_and_sum(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                sub_total, sub_count = flatten_and_sum(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = flatten_and_sum(lst)
    if total_count == 0:
        return 0  # avoid division by zero
    return total_sum / total_count

nested_list = [[10, 20], [30, 40, 50], [60]]

result = average_nested(nested_list)

print("Nested list:", nested_list)
print("Average of all elements:", result)

Nested list: [[10, 20], [30, 40, 50], [60]]
Average of all elements: 35.0


10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:


In [ ]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [ ]:
empty_array = np.empty((2,2))
print("1. Empty array 2x2:\n", empty_array, "\n")

1. Empty array 2x2:
 [[3.02679359e-315 0.00000000e+000]
 [6.74898061e-310 6.74898061e-310]] 



2. Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((4,2))
print("2. All-one array 4x2:\n", ones_array, "\n")

2. All-one array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
filled_array = np.full((3,3), fill_value=7)  # Example: 3x3 filled with 7
print("3. Filled array 3x3 with 7:\n", filled_array, "\n")

3. Filled array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 



4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
sample_array = np.array([[1,2,3],[4,5,6]])
zeros_like_array = np.zeros_like(sample_array)
print("4. Zeros array like sample_array:\n", zeros_like_array, "\n")

4. Zeros array like sample_array:
 [[0 0 0]
 [0 0 0]] 



5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like_array = np.ones_like(sample_array)
print("5. Ones array like sample_array:\n", ones_like_array, "\n")

5. Ones array like sample_array:
 [[1 1 1]
 [1 1 1]] 



6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Numpy array from list:\n", array_from_list)

6. Numpy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:

In [ ]:
import numpy as np

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array1 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", array1, "\n")

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 



2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
matrix2 = np.arange(0, 9).reshape(3,3)
print("2. 3x3 matrix from 0 to 8:\n", matrix2, "\n")


2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 



3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity3 = np.eye(3)
print("3. 3x3 identity matrix:\n", identity3, "\n")

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array4 = np.random.random(30)
mean4 = random_array4.mean()
print("4. Random array of size 30:\n", random_array4)
print("Mean of array:", mean4, "\n")

4. Random array of size 30:
 [0.9397817  0.55655803 0.005015   0.90654639 0.39720172 0.07452534
 0.34945906 0.11141966 0.65085488 0.91408411 0.46037046 0.26011026
 0.0341184  0.90394301 0.97972418 0.85996808 0.90091152 0.25530206
 0.71850889 0.54893462 0.87542094 0.17934883 0.80021099 0.72144892
 0.53104067 0.25000647 0.1546743  0.15812383 0.08659014 0.42096012]
Mean of array: 0.5001720859995761 



5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array5 = np.random.random((10,10))
min5 = random_array5.min()
max5 = random_array5.max()
print("5. 10x10 random array:\n", random_array5)
print("Minimum value:", min5)
print("Maximum value:", max5, "\n")

5. 10x10 random array:
 [[0.6004913  0.1771753  0.29887716 0.31714618 0.87918471 0.28807755
  0.79364122 0.35106693 0.2629442  0.36123272]
 [0.07732179 0.02277289 0.72485451 0.31449351 0.88334212 0.51104644
  0.4916718  0.82790084 0.06673178 0.53510043]
 [0.12621556 0.02470626 0.68075421 0.07322366 0.83270499 0.6841564
  0.60598398 0.41411677 0.42064159 0.53553654]
 [0.93229084 0.04372399 0.30158662 0.6962825  0.84658325 0.71268136
  0.62160665 0.43183252 0.36837278 0.5628846 ]
 [0.83484797 0.33298092 0.63524862 0.60954464 0.67569772 0.0925478
  0.67392216 0.39124262 0.15704644 0.31942487]
 [0.65466883 0.08544393 0.04024652 0.08123763 0.23753579 0.97698868
  0.747877   0.38215255 0.15884769 0.80976209]
 [0.10609305 0.0030948  0.24729899 0.97662527 0.61232543 0.12629734
  0.01406589 0.29230126 0.45848177 0.19733191]
 [0.2429463  0.32863856 0.36441806 0.41526579 0.3632087  0.81405958
  0.27205695 0.51687836 0.79430137 0.16180475]
 [0.89346274 0.12982128 0.82565692 0.20207303 0.94630835 0

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array6 = np.zeros(10)
zero_array6[4] = 1  # index 4 is the 5th element
print("6. Zero array with 5th element as 1:\n", zero_array6, "\n")

6. Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 



7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr7 = np.array([1,2,0,0,4,0])
reversed_arr7 = arr7[::-1]
print("7. Reversed array:\n", reversed_arr7, "\n")


7. Reversed array:
 [0 4 0 0 2 1] 



8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
n = 5
border8 = np.ones((n,n))
border8[1:-1,1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:\n", border8, "\n")

8. 2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 



9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checker9 = np.zeros((8,8))
checker9[1::2, ::2] = 1
checker9[::2, 1::2] = 1
print("9. 8x8 checkerboard pattern:\n", checker9)

9. 8x8 checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.

In [ ]:
add_xy = x + y
print("1. Addition of x and y:\n", add_xy, "\n")

1. Addition of x and y:
 [[ 6  8]
 [10 13]] 



2. Subtract the two array.

In [ ]:
sub_xy = x - y
print("2. Subtraction of x and y:\n", sub_xy, "\n")

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]] 



3. Multiply the array with any integers of your choice.

In [ ]:
mul_x = x * 2
print("3. x multiplied by 2:\n", mul_x, "\n")

3. x multiplied by 2:
 [[ 2  4]
 [ 6 10]] 



4. Find the square of each element of the array.

In [ ]:
square_x = x ** 2
print("4. Square of each element in x:\n", square_x, "\n")

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]] 



5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("5a. Dot product v and w:", dot_vw)
print("5b. Dot product x and v:\n", dot_xv)
print("5c. Dot product x and y:\n", dot_xy, "\n")

5a. Dot product v and w: 219
5b. Dot product x and v:
 [29 77]
5c. Dot product x and y:
 [[19 22]
 [50 58]] 



6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_cols = np.vstack((v, w)).T

print("6a. Concatenate x and y along rows:\n", concat_xy_rows)
print("6b. Concatenate v and w along columns:\n", concat_vw_cols, "\n")

6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]] 



For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

1. Prove A.A−1 = I.

In [ ]:
# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)   # inverse of A
result1 = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A^-1:\n", result1)
print()

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]



2. Prove AB ̸= BA.

In [ ]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)
print()

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]



3. Prove (AB)

T = BTAT

In [ ]:
left_side = (AB).T
right_side = np.dot(B.T, A.T)

print("(AB)^T:\n", left_side)
print("B^T A^T:\n", right_side)
print()

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]



Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# Coefficient matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

# Constant matrix B
B = np.array([-1, -3, 9])

# Inverse of A
A_inv = np.linalg.inv(A)

# Solve X = A^-1 * B
X = np.dot(A_inv, B)

print("Solution [x, y, z]:")
print(X)

Solution [x, y, z]:
[ 2.  1. -2.]


In [1]:
import numpy as np
import time
import random

# ---------- 1. Element-wise Addition ----------
size = 1000000

# Python Lists
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

start = time.time()
result_list_add = [list1[i] + list2[i] for i in range(size)]
end = time.time()

print("Python List Addition Time:", end - start)


# NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_np_add = arr1 + arr2
end = time.time()

print("NumPy Array Addition Time:", end - start)


# ---------- 2. Element-wise Multiplication ----------

# Python Lists
start = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()

print("Python List Multiplication Time:", end - start)


# NumPy Arrays
start = time.time()
result_np_mul = arr1 * arr2
end = time.time()

print("NumPy Array Multiplication Time:", end - start)


# ---------- 3. Dot Product ----------

# Python Lists
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()

print("Python List Dot Product Time:", end - start)


# NumPy Arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start)


# ---------- 4. Matrix Multiplication ----------

n = 1000

# Python Lists (matrix)
A = [[random.random() for _ in range(n)] for _ in range(n)]
B = [[random.random() for _ in range(n)] for _ in range(n)]

start = time.time()

result = [[0]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start)


# NumPy Matrix Multiplication
A_np = np.random.random((n,n))
B_np = np.random.random((n,n))

start = time.time()
result_np = np.dot(A_np, B_np)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

Python List Addition Time: 0.11071634292602539
NumPy Array Addition Time: 0.004408836364746094
Python List Multiplication Time: 0.11330223083496094
NumPy Array Multiplication Time: 0.0048329830169677734
Python List Dot Product Time: 0.10493183135986328
NumPy Dot Product Time: 0.002061605453491211
Python List Matrix Multiplication Time: 350.80743980407715
NumPy Matrix Multiplication Time: 0.12027621269226074
